- name: "memory"
  color: "c2fbd7"
  description: "Задачи подсистемы памяти"
- name: "memory-bug"
  color: "ffb3ba"
  description: "Ошибки в логике памяти или данных"
- name: "memory-feature"
  color: "b5d8ff"
  description: "Новые возможности или улучшения памяти"
- name: "memory-docs"
  color: "f7e6a8"
  description: "Документация и описания, связанные с памятью"
